spring:
  application.name: zuul-proxy
  main:
    allow-bean-definition-overriding: true
server.port: 8888
#  ssl.enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka/
#      defaultZone: ${cloud1}/eureka/,${cloud1}/eureka/
    allow-redirects: true
zuul:
  sensitive-headers: Set-Cookie
  routes:
    eureka:
      path: /t/**
      url: http://127.0.0.1:8080
